(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

(depends-on "zygospore")
(depends-on "helm-gtags")
(depends-on "helm")
(depends-on "ws-butler")
(depends-on "volatile-highlights")
(depends-on "undo-tree")
(depends-on "iedit")
(depends-on "dtrt-indent")
(depends-on "counsel-projectile")
(depends-on "company")
(depends-on "clean-aindent-mode")
(depends-on "anzu")

(depends-on "yatex" :hg "http://www.yatex.org/hgrepos/yatex")
